server.port = 8081
spring.application.name=VaultGuard
spring.datasource.url=jdbc:postgresql://localhost:5432/vaultguard_db
spring.datasource.username=postgres
spring.datasource.password=kwyjibo

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.cloud.vault.enabled=true
spring.cloud.vault.url = http://localhost:8200
spring.cloud.vault.token = hvs.I88sfbW68FsRfy4g31jIDb9E
spring.cloud.vault.kv.enabled=true

spring.cloud.vault.scheme=http
spring.cloud.vault.uri=http://localhost:8200