server.port = 8081
spring.application.name=VaultGuard
spring.datasource.url=jdbc:postgresql://localhost:5432/vaultguard_db
spring.datasource.username=postgres
spring.datasource.password=kwyjibo

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Disable Spring Cloud Vault auto-config until Vault is configured
spring.cloud.vault.enabled=false

spring.session.store-type=none