server.port=8081
spring.application.name=VaultGuard

spring.datasource.url=jdbc:postgresql://localhost:5432/vaultguard_db
spring.datasource.username=postgres
spring.datasource.password=kwyjibo
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.cloud.vault.ssl.enabled=false
spring.cloud.vault.enabled=true
spring.cloud.vault.uri=http://localhost:8200
spring.cloud.vault.scheme=http
spring.cloud.vault.token=root
spring.cloud.vault.kv.enabled=true
spring.cloud.vault.authentication=TOKEN

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.database=0
spring.data.redis.repositories.enabled=false

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=599a9d248ace96
spring.mail.password=327f98b25801c1
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true